// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdbgemfqzquykwwgxwur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYmdlbWZxenF1eWt3d2d4d3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTMxNTQsImV4cCI6MjA2MzQ4OTE1NH0.upfmMiNxuln4xbWpeI8N6RvxNVkxpqUu1ePzYoC4dkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);